title: Alice's Little Corner
email: alice@thatoneali.se
description: My personal website, and I be Alice. Duh. Du-u-u-uh.
github_username: thatonealise

baseurl: "/"
url: "https://thatoneali.se"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/ruby/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/